# Generated by Django 5.2.17 on 2026-09-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="is_deal_of_the_day",
            field=models.BooleanField(default=False),
        ),
    ]
