# Generated by Django 6.1.1 on 2026-09-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_is_deal_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimage',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
