# Generated by Django 6.1.1 on 2026-09-23 19:16
# No-op: Products.id and ProductsImage.id are already defined as UUIDField in 0001_initial

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productsimage_images'),
    ]

    operations = [
    ]

