# Generated by Django 6.1.1 on 2026-09-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_description_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='products',
            name='specs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='products',
            name='storage_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
