# Generated by Django 6.1.1 on 2026-09-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_products_badge_products_colors_products_specs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='i_gadgets/brands/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='i_gadgets/categories/'),
        ),
        migrations.AddField(
            model_name='productsimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='i_gadgets/products/'),
        ),
    ]
