# Generated by Django 5.2.17 on 2026-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('primary_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('badge_text', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PromoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('action_link', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('exclusive_offer', 'Exclusive Offer'), ('deal_of_day', 'Deal of the Day'), ('member_benefits', 'Member Benefits')], max_length=50, unique=True)),
            ],
        ),
    ]
