# Generated by Django 6.1.1 on 2026-09-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='i_gadgets/banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
