# Generated by Django 5.2.17 on 2026-09-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
