# Generated by Django 6.1.1 on 2026-09-25 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('user_type', models.CharField(default='guest', max_length=20)),
                ('user_identifier', models.CharField(default='Guest Visitor', max_length=255)),
                ('action', models.CharField(choices=[('view_product', 'Viewed Product'), ('add_to_cart', 'Added to Cart'), ('remove_from_cart', 'Removed from Cart'), ('add_to_wishlist', 'Saved to Wishlist'), ('remove_from_wishlist', 'Removed from Wishlist'), ('checkout_start', 'Initiated Checkout'), ('order_placed', 'Placed Order'), ('search', 'Searched Products')], max_length=50)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_title', models.CharField(blank=True, default='', max_length=255)),
                ('product_image', models.TextField(blank=True, default='')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
