# Generated by Django 6.1.1 on 2026-09-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
