# Generated by Django 5.2.17 on 2026-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', help_text='Phone number for order confirmation calls', max_length=11),
        ),
    ]
