# Generated by Django 6.1.1 on 2026-09-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_phone_number_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_dhaka_fee', models.DecimalField(decimal_places=2, default=70.0, help_text='Delivery fee inside Dhaka (BDT)', max_digits=10)),
                ('outside_dhaka_fee', models.DecimalField(decimal_places=2, default=130.0, help_text='Delivery fee outside Dhaka (BDT)', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=5000.0, help_text='Order amount threshold for free shipping (0 to disable)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Setting',
                'verbose_name_plural': 'Delivery Settings',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='customer_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default='', help_text='Customer email', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Customer name', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('inside_dhaka', 'Inside Dhaka'), ('outside_dhaka', 'Outside Dhaka')], default='inside_dhaka', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=10),
        ),
    ]
