# Generated by Django 6.1.1 on 2026-09-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliverysetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverysetting',
            name='free_shipping_threshold',
        ),
    ]
