# Generated by Django 6.1.1 on 2026-09-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_deliverysetting_free_shipping_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_color',
            field=models.CharField(blank=True, default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_storage',
            field=models.CharField(blank=True, default='Standard', max_length=100),
        ),
    ]
